/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ketch.kotlin-library-conventions")
}

val kotestVersion: String by project
val jibVersion: String by project
val kotlinxCoroutinesCoreVersion: String by project
val kotlinxCliVersion: String by project

dependencies {
//    implementation(enforcedPlatform("io.kotest:kotest-bom:$kotestVersion"))
    implementation("io.kotest:kotest-framework-api-jvm:$kotestVersion")
    implementation("io.kotest:kotest-framework-engine-jvm:$kotestVersion")

    implementation(kotlin("stdlib"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinxCoroutinesCoreVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-cli:$kotlinxCliVersion")

    testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion")
}

val compileKotlin: org.jetbrains.kotlin.gradle.tasks.KotlinCompile by tasks

compileKotlin.kotlinOptions {
    freeCompilerArgs = listOf("-Xinline-classes")
}
